In [1]:
import numpy as np
a = [1, 2, 3, 4, 5]
b = np.array(a)
print(type(b))
print(b)


<class 'numpy.ndarray'>
[1 2 3 4 5]


In [13]:
s = np.arange(8, 17, 3)
t = np.eye(6)
print(s)
print(s.dtype)


[ 8 11 14]
int32


In [14]:
t1 = np.eye(3)
np.linspace(0, 1, 4)
np.random.randn(3)
print(t1)
d = t1.reshape(9)
print(d)
print(d.shape)
print(t1.shape)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 0. 0. 0. 1. 0. 0. 0. 1.]
(9,)
(3, 3)


In [15]:
import numpy as np
a1 = [2, 5, 7, 18, 20, 6, 45]
b1 = np.array(a1)
print(b1[2:5])
print(b1[3:])


[ 7 18 20]
[18 20  6 45]


In [16]:
b1[1:4] = 40
print(b1)
# b2 = b1
b2 = b1.copy()
b2[:2] = 100
print(b2)
print(b1)


[ 2 40 40 40 20  6 45]
[100 100  40  40  20   6  45]
[ 2 40 40 40 20  6 45]


Two dimensional array

In [43]:
arr_2d = np.array([[2, 4, 5], [10, 34, 5], [9, 0, 2]])
print(arr_2d[1][2])
print(arr_2d[1, 2])
# print(arr_2d[:2][1:])
print(arr_2d[:1][0][1:])
print(arr_2d[1:][1])
print(arr_2d[:1, 1:])


5
5
[4 5]
[9 0 2]
[[4 5]]


In [3]:
import numpy as np
arr = np.arange(1, 11)
bool_arr = arr < 4
print(arr[bool_arr])


[1 2 3]


In [7]:
x = np.arange(50).reshape(5, 10)
# print(x)
print(x[1:3, 3:5])
print(x[1, 0]*arr)
print(arr**3)


[[13 14]
 [23 24]]
[ 10  20  30  40  50  60  70  80  90 100]
[   1    8   27   64  125  216  343  512  729 1000]
